### PR TITLE
fixed a micro mistake of stagnation p & T

### PR DESCRIPTION
**Pull request by WenyinWei**

### CODE REVIEW

**Comment by WenyinWei** [comment]
Hello all,

Would you mind changing full names of all physical variables to symbols? Or give symbols first, with full names behind them. That would make the tutorial more readable for readers with hydrodynamics background knowledge.

**Comment by economon** [comment]
Hi @WenyinWei : I am not sure I understand your request fully, but please don't hesitate to propose any changes you would like. We really would like to encourage more collaboration on the documentation through GitHub as well (like we have for the code already). Thanks!

**Comment by WenyinWei** [comment]
Oh, I should have added some more info in the conversation panel. The pull request is initialized due to a small typo of the stagnation pressure & temperature. It is just a small typo 8437b5a140997871bfa6ab56622e34f9f1138795 and I will report more in this pull request. Additionally, would you like to change the variable names appearing in the .md files to their conventional symbols in fluid dynamics, that would be much more understandable and concise? A table of the variable names can be added at the beginning of the end of the page.

**Comment by economon** [comment]
@WenyinWei : we're happy to consider any changes you would like to make if you feel it makes the documentation more clear. Thanks for helping improve the docs

**Comment by WenyinWei** [comment]
Oh, sorry for being late to edit, I will add more these days. Thanks for your remind~

**Comment by TobiKattmann** [comment]
I'll merge this in now as this fixes a mistake... and quite some time passed without an movement here :)

Thanks for the contribution @WenyinWei :bouquet: if you're still interested in adding a version with more symbols I would ask you just to open a new PR. I do like the idea of adding more symbols because it is much more intuitive to understand at a glance. Adding latex style formulas is pretty straight forward just put the LaTeX code into double dollar like so `$$\rho$$`

**Pull request merged**
