### PR TITLE
Linear solver docs

### PR DESCRIPTION
**Pull request by pcarruscag**
I started a linear solver and preconditioners page, additions from the community based on their own experience are welcome.

### CODE REVIEW

**Comment by clarkpede** [comment]
I would add something about the number of iterations on the linear solver and/or the accuracy.  You could say something like:
### Linear solver accuracy

For steady fluid problems and dual-time stepping problems, there are two sets of iterations used for solving the system of equations.  There are the inner or linear iterations, where a linear algebra problem is solved for each pseudo time-step.  Then there are the outer or nonlinear iterations, where the solution is advanced in pseudo time. For RANS problems, there is little advantage to solving the inner iterations to a high degree of precision. The outer iterations are usually the limiting factor in convergence.  The setting `LINEAR_SOLVER_ITER` can be left relatively low (5-50) and the `LINEAR_SOLVER_ERROR` can be in the range 1.0E-2 - 1.0E-8.  As an example, using the JST central scheme and the SST turbulence model on the RAE2822 case, [Palacios et al.](https://doi.org/10.2514/6.2014-0243) found no advantage in going beyond  `LINEAR_SOLVER_ERROR=1E-2`.  The number of nonlinear iterations remained the same, even when the accuracy of the linear solver was increased.

**Comment by pcarruscag** [comment]
I tried to convey that kind of consideration in:
https://github.com/su2code/su2code.github.io/blob/linsol_and_MG/_docs/Linear-Solvers-and-Preconditioners.md#fluid-simulations
But good point on the number of iterations, I did not have ranges for them.
By the way, I have a feeling the systems get a bit easier to solve for time-domain problems, since you do unsteady simulations more often, is that true? or did I make it up?

**Comment by clarkpede** [comment]
Ah, I see where you talked about iterations.  Yeah, what you have may be sufficient. 

As far as unsteady problems go, it depends on the application.  For my type of application (scale-resolving simulations of turbulence), we want to resolve individual eddies advecting through the grid.  For that case, you want the your unsteady convective CFL <= 1. Even if you can maintain accuracy past CFL = 1, you can't track the individual eddies anymore.  So we always keep the convective CFL <= 1.

As for dual-time stepping, I don't know what the CFL requirements are for the pseudo-time marching.

**Comment by talbring** [comment]
Thanks @pcarruscag ! We need more of those documents, that's really useful.

**Comment by pcarruscag** [comment]
@talbring should files be added to "_docs" or "_docs_v7" (or both)?

**Comment by talbring** [comment]
@pcarruscag The idea is to add new things from now on to the _docs_v7 folder so that we have a smooth transition. The new documentation is available at https://su2code.github.io/docs_v7. Once the release is done we will change the links on the website to the new docs. I will add the one from this PR manually.

**Comment by pcarruscag** [comment]
Ok got it. Thanks.

Tim Albring <notifications@github.com> escreveu no dia segunda, 28/10/2019
à(s) 12:25:

**Pull request merged**
