### PR TITLE
Add streamwise periodic tutorial and theory.

### PR DESCRIPTION
**Pull request by TobiKattmann**
This adds a 2D tutorial (+ some images for that) and a theory section. Some links will not work unless the additions to the Tutorials and Testcases which are/will be merged into develop find their way into master.

Everything else is tested locally.

### CODE REVIEW

**Comment by pcarruscag** [comment]
Does this mean that your record-holding PR is ready to go into develop? :)

**Comment by TobiKattmann** [comment]
Let me quote one of your more famous countrywoman:
`All good things come to an end` - Nelly Furtado, 2006

(While reading her Wikipedia article I also found your inspiration for the name of Fado ;) )

**Comment by TobiKattmann** [comment]
not sure about the 'good' part though :)

**Comment by pcarruscag** [comment]
Genuine Lol from Portugal. Go hit that "ready for review"  then.

**Comment by TobiKattmann** [comment]
merging in after the merge of su2code/su2/pull/773 into develop

**Pull request merged**
