### PR TITLE
Update and enhance CHT tutorial

### PR DESCRIPTION
**Pull request by oleburghardt**
This PR moves the Conjugate Heat Transfer tutorial from the incompressible flow to the multiphysics section.

The chapter on results is enhanced by a short validation study of discrete adjoint solutions against finite differences based on a single FFD box design variable.

### CODE REVIEW

**Comment by Nicola-Fonzi** [comment]
Dear @oleburghardt, I committed a small modification to avoid a conflict between two tutorials, please let me know if it is fine for you

**Comment by oleburghardt** [comment]
Hi @Nicola-Fonzi sorry for the late reply, the .io section is not yet on my radar. All fine, thanks!

**Comment by Nicola-Fonzi** [comment]
Dear @oleburghardt, no problem! I merged the PR as I thought it was a silent consent. The related tutorial files are also in place

**Comment by oleburghardt** [comment]
Absolutely, thanks again for going ahead. I'll try to resuscitate the unsteady CHT one, it would lign up nicely with the unsteady FSI one :)

**Comment by Nicola-Fonzi** [comment]
Yes it would definitely be very symmetric :)

**Pull request merged**
