### PR TITLE
Revert "Merge develop into master"

### PR DESCRIPTION
**Pull request by pcarruscag**
Reverts su2code/su2code.github.io#38

### CODE REVIEW

**Comment by pcarruscag** [comment]
@TobiKattmann the ideia is to merge develop into master when a new release is created
otherwise you have the wrong documentation for master

**Comment by TobiKattmann** [comment]
Ups sorry the trouble, I did not think about that. Lightning fast reaction tho :horse_racing:

**Comment by pcarruscag** [comment]
No prob, we were not using develop much for this repo, but I guess we should try to follow the same strategy everywhere.

**Comment by TobiKattmann** [comment]
FYI: Due to this little merry-go-round session we had with this PR it seems that merging the develop into the master does not add your changes. Cherry-picking 18e9f68 brings them back to life :vampire: so when the next su2 master is released then I'll take care about that.

**Pull request merged**
