### PR TITLE
Flat Plates(T3A and T3A-) VandV and Tutorial for LM model

### PR DESCRIPTION
**Pull request by sun5k**
VandV and tutorial for LM model, this description summary of [LM model PR#1751](https://github.com/su2code/SU2/pull/1751)

### CODE REVIEW

**Comment by pcarruscag** [comment]
This is very nice :+1: 
Add a link to the new v&v page here https://github.com/sun5k/su2code.github.io/blob/master/_vandv/index.md please.
And one here for the tutorial https://github.com/sun5k/su2code.github.io/blob/master/_tutorials/index.md

**Comment by sun5k** [comment]
> This is very nice 👍 Add a link to the new v&v page here https://github.com/sun5k/su2code.github.io/blob/master/_vandv/index.md please. And one here for the tutorial https://github.com/sun5k/su2code.github.io/blob/master/_tutorials/index.md

Thank you, I missed the Index.md files. Index files are updated.
I have a question for index.md.  

https://github.com/su2code/su2code.github.io/blob/master/_vandv/index.md 
https://github.com/su2code/su2code.github.io/blob/master/_tutorials/index.md

Above index files, the case links are missing. Is it change the directory?

**Comment by sun5k** [comment]
> I don't follow, what links are missing?

ex) 

In the VandV index. 

https://github.com/su2code/su2code.github.io/edit/master/_vandv/index.md

Last part : 


---------------------------------


## Summary of V&V case studies
* [Method of Manufactured Solutions for Compressible Navier-Stokes](/vandv/MMS_FVM_Navier_Stokes/)
Formal order of accuracy of the finite volume solver in SU2 for the laminar Navier-Stokes equations is assessed.
* [2D Zero Pressure Gradient Flat Plate RANS Verification Case](/vandv/Flat_Plate/)
Code-to-code comparisons of drag and skin friction on a turbulent flat plate is presented using data from the NASA Turbulence Modeling Resource.
* [2D Bump-in-Channel RANS Verification Case](/vandv/Bump_Channel/)
Code-to-code comparisons for a bump in a channel, which results in pressure gradients, is presented using data from the NASA Turbulence Modeling Resource.
* [Three-Element High-Lift Subsonic Airfoil](/vandv/30p30n/)
Results for the 30p30n airfoil, mesh independence study at low angle-of-attack, and determination of maximum lift, both comparing different numerical schemes.
* [Shock-Wave Boundary-Layer Interaction](/vandv/swbli/)
Comparison of grid-converged results with experimental data. SA and SST turbulence models.



---------------------------------


The above links can't show the correct page. I guess the directory was changed.

**Comment by pcarruscag** [comment]
Oh I see, the links are setup for the website (https://su2code.github.io/vandv/home/) when github tries to follow them something goes wrong but that is ok.
If you follow the same pattern as other v&v pages all should be fine in the website.

**Review by pcarruscag — APPROVED** [review]

**Pull request merged**
