### PR TITLE
Tutorial actuator disk with variable load

### PR DESCRIPTION
**Pull request by EttoreSaetta**
Hello to everyone,
I am writing a tutorial to explain how to use the actuator disk model with variable load.
The actuator disk model considered is the one developed within the PR #1027 in the SU2 repository.
This tutorial is still a draft, it will be updated and completed in the next few days.
I hope that this could be useful for the SU2 community.

### CODE REVIEW

**Review by pcarruscag — APPROVED** [review]
Thank you Ettore, the tutorial looks very nice.
If you want you can move the test case from TestCases to Tutorials, this way when someone clones the tutorials repository they get the files right away.
There is a regression case script for the tutorials so your tests would still run.

**Comment by EttoreSaetta** [comment]
> Thank you Ettore, the tutorial looks very nice.
> If you want you can move the test case from TestCases to Tutorials, this way when someone clones the tutorials repository they get the files right away.
> There is a regression case script for the tutorials so your tests would still run.

Hello Pedro, thanks for giving it a look.
There are still some small changes that I have to do.
You mean that I should move the grid from the TestCase repository to the Tutorials repository, or should I copy it there?
Because I have seen that many test cases are in both repositories.

**Comment by pcarruscag** [comment]
I think maybe people duplicated other examples to make the tutorials accessible without downloading the entire TestCases repository.
If moving the files required for your tutorial is an option, I think it would be a good idea. But if it would require duplicating mesh files maybe it would be better to leave it like this.
Whatever you decide is fine, having tutorials is much more important than these details.
Just try to include this in the tutorial regressions to make sure we don't break this because of some config option for example.

**Comment by EttoreSaetta** [comment]
I have opened a PR in the Tutorials repository to upload the files required for this tutorial.
Once these files are only in the Tutorials repository, and not anymore in the TestCases, is it a problem for the SU2 regressions?
As regard the tutorial regressions, are you talking about the tutorials.py in the TestCases folder of the SU2 repository?
If so, in order to do that, should I open a new PR in the SU2 repository?
I'm sorry for all these questions, but it is the first time for me.
Thank you in advance.

**Comment by pcarruscag** [comment]
> Once these files are only in the Tutorials repository, and not anymore in the TestCases, is it a problem for the SU2 regressions?

The tutorials are also cloned when the regressions are run, but to a different location so it will probably be a problem.

> As regard the tutorial regressions, are you talking about the tutorials.py in the TestCases folder of the SU2 repository?
If so, in order to do that, should I open a new PR in the SU2 repository?

Yes tutorials.py, In your case you would probably move the regression in parallel_regression.py to tutorials.
The simplest would be to modify Tutorial and Testcases and then SU2.

**Comment by EttoreSaetta** [comment]
> Yes tutorials.py, In your case you would probably move the regression in parallel_regression.py to tutorials.
> The simplest would be to modify Tutorial and Testcases and then SU2.

Perfect, thank you so much for your help.
Now I will provide to do these changes.

**Pull request merged**
